[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "v1.0.2"

# Kubernetes >= 1.10.
# Note: Change all at once.
[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.5"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.10.5"

# Fixes pinning versions for other dependencies with not correct dependency settings.

# Fix for "k8s.io/apimachinery"
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[prune]
  go-tests = true
  unused-packages = true