[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

# Kubernetes >= 1.10.
# Note: Change all at once.
[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0-rc.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0-rc.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0-rc.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.0-rc.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.10.0-rc.1"

[prune]
  go-tests = true
  unused-packages = true