apiVersion: chaos.spotahome.com/v1alpha1
kind: PodTerminator
metadata:
  name: nginx-controller
  labels:
    example: pod-terminator-operator
    operator: pod-terminator-operator
spec:
  selector:
    k8s-app: nginx-ingress-controller
  periodSeconds: 120
  TerminationPercent: 25
  MinimumInstances: 2
  #DryRun: true

